### PR TITLE
[JetNews] Move AppDrawer Composable from JetnewsApp.kt to AppDrawer.kt

### PR DESCRIPTION
**Pull request by takahirom**
Thanks for the many high quality samples!

I'm currently considering how to split files when building an app with Compose.
So I noticed that AppDrawer() used to be called by JetnewsApp() and now it's called by HomeScreen() and InterestsScreen(), and that AppDrawer() stays in JetnewsApp.kt. (https://github.com/android/compose-samples/commit/aafa9ad67bd13695582a4ececf244f42eb28e76c#diff-098e0ebfb55fd1512e2e230dca256aaab9e14bdee57e7317f04dace7061d5803L61 ) 
Therefore, I moved it. 
And there were previews such as PreviewJetnewsApp() and PreviewJetnewsAppDark(), but since it was a function for previewing AppDrawer, I changed it to PreviewAppDrawer().

### CODE REVIEW

**Comment by takahirom** [comment]
Added space to commit message.
`[JetNews]" "Move AppDrawer Composable from JetnewsApp.kt to AppDrawer.kt`

**Review by objcode — APPROVED** [review]

**Comment by objcode** [comment]
@yrezgui can you include this with the alpha07 changes?

**Comment by takahirom** [comment]
I rebased and fixed the import conflict. (with https://github.com/android/compose-samples/commit/b0e28edbda08666652fb49669d4162ab868c07d4#diff-098e0ebfb55fd1512e2e230dca256aaab9e14bdee57e7317f04dace7061d5803L21 )

**Comment by yrezgui** [comment]
@takahirom, can you create another PR targeting the `main` branch as we've merged the alpha07 samples?

**Comment by nickbutcher** [comment]
*targeting `dev_alpha08`

**Comment by takahirom** [comment]
Of course :)

**Pull request closed without merging**
