### PR TITLE
Set kotlinOptions.jvmTarget to 1.8 #1109

### PR DESCRIPTION
**Pull request by obask**
...to make samples compatible with AGP 8.0.0
and Android Studio Flamingo

### CODE REVIEW

**Comment by obask** [comment]
related issue: https://issuetracker.google.com/issues/277272832

**Comment by astamato** [comment]
As per latest main, samples are already compatible with AGP 8.0.0, why do we need this? cc @mlykotom

**Comment by obask** [comment]
No it's not necessary, because samples have been updated to JDK17 which is default for AGP 8.0 and kotlin 1.8.0

**Comment by obask** [comment]
There are some minor inconsistencies, but these aren't important:
Jetsurvey is setting java 17 explicitly while other samples rely on the default value:
https://github.com/android/compose-samples/blob/main/Jetsurvey/app/build.gradle.kts#L52
```
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
```

**Pull request closed without merging**
