### PR TITLE
Updates the Android Gradle Plugin to 4.2.0-alpha10

### PR DESCRIPTION
**Pull request by AOrobator**

### CODE REVIEW

**Comment by nickbutcher** [comment]
Thanks for the PR but we're changing our process a little and will be removing the `develop` branch. I re-targetted this to the `dev_alpha02` branch but there are now some conflicts. If you want to address we can try and land this **but** we plan to pick up the same changes in our work to update all samples to `alpha03` in the `dev_alpha03` branch soon.

**Comment by AOrobator** [comment]
@googlebot I consent.

**Comment by AOrobator** [comment]
@nickbutcher I resolved the merge conflict through Github's UI (didn't even know I could do that!) but now the CLA is failing. I give consent for my commits to be included

**Comment by JoseAlcerreca** [comment]
Closing as it's obsolete.

Thanks for the changes!

**Pull request closed without merging**
