### PR TITLE
Removes Rally and fixes READMEs

### PR DESCRIPTION
**Pull request by JoseAlcerreca**

### CODE REVIEW

**Review by yrezgui — APPROVED** [review]

**Comment by yrezgui** [comment]
Don't merge it yet, beta09 release of codelabs is still ongoing (found a bug in our tests)

**Comment by JoseAlcerreca** [comment]
But this is samples.

**Review by manuelvicnt — APPROVED** [review]

**Comment by yrezgui** [comment]
It's not really blocking, my bad. Feel free to merge

**Comment by JoseAlcerreca** [comment]
Thanks!

**Pull request merged**
