### PR TITLE
Adding back press from Article screen

### PR DESCRIPTION
**Pull request by rczh**
Fix bug that app could not back to home screen when press back key from Article screen

### CODE REVIEW

**Comment by rczh** [comment]
@googlebot I signed it!

**Comment by rczh** [comment]
@googlebot I signed it!

**Comment by rczh** [comment]
@googlebot I fixed it.

**Comment by nickbutcher** [comment]
Thanks for the PR. As stated in the app, we've kept the navigation scheme purposefully simple as a "proper" navigation solution is not available yet. We'd prefer not to add more navigation code which detracts from the purpose of this sample and potentially signals that this is your responsibility to solve.

Closing this PR but thank you so much for the contribution. In the future, feel free to open an issue before submitting a PR to discuss potential contributions.

**Pull request closed without merging**
