### PR TITLE
resolved issue 42

### PR DESCRIPTION
**Pull request by amar1995**
Resolved the issue#42 where navigation content is hardly clickable.

### CODE REVIEW

**Comment by amar1995** [comment]
@googlebot I fixed it.

**Comment by amar1995** [comment]
@googlebot I fixed it.

**Comment by amar1995** [comment]
@googlebot I fixed it.

**Comment by amar1995** [comment]
@googlebot I fixed it.

**Comment by nickbutcher** [comment]
Fixed in #45

**Pull request closed without merging**
