### PR TITLE
[All] Update to beta02

### PR DESCRIPTION
**Pull request by yrezgui**
Waiting for #436 to be merged

### CODE REVIEW

**Review by yaraki — APPROVED** [review]

**Comment by Luis0648** [comment]
Automatized*#*#

**Comment by Luis0648** [comment]
Actived#*#*

**Comment by Luis0648** [comment]
Yess!!

**Comment by Luis0648** [comment]
Reactivated ye permisions decide google robot

**Comment by Luis0648** [comment]
Yess

**Pull request merged**
