### PR TITLE
README: Update AS Canary version & added download link

### PR DESCRIPTION
**Pull request by aeab13**
Hello,

I want to propose 2 changes to the README:
- Updated recommended AS canary version to Arctic Fox 2020.3.1.
- Add a link that takes directly to the AS canary download page.

About the first point, in my opinion I'd completely remove the version from the text and just leave it as "the lastest Canary version of Android Studio).

### CODE REVIEW

**Comment by aeab13** [comment]
@googlebot I signed it!

**Comment by nickbutcher** [comment]
+1 to changing to just “the latest Canary version of Android Studio”—can you update this PR?

I've also re-targeted to the latest dev branch.

**Comment by aeab13** [comment]
> +1 to changing to just “the latest Canary version of Android Studio”—can you update this PR?
Updated!

**Review by nickbutcher — APPROVED** [review]

**Comment by nickbutcher** [comment]
Thanks!

**Pull request merged**
