### PR TITLE
Changed usage of mutex with update method of mutable state flow to atomically update values of it.

### PR DESCRIPTION
**Pull request by kl3jvi**

### CODE REVIEW

**Review by riggaroo — APPROVED** [review]
Thanks for the contribution :)

**Comment by kl3jvi** [comment]
> Thanks for the contribution :)

No problem at all ^^

**Comment by riggaroo** [comment]
Can you run formatting on it? `./scripts/format.sh ` Thanks!

**Comment by kl3jvi** [comment]
> Can you run formatting on it? `./scripts/format.sh ` Thanks!

@riggaroo  Just did format

**Comment by kl3jvi** [comment]
@riggaroo can u recheck if is ok now?

**Comment by kl3jvi** [comment]
Ready for merge I guess :')

**Pull request merged**
