### PR TITLE
[JetChat] Adding Downloadable Fonts implementation

### PR DESCRIPTION
**Pull request by astamato**
Jetchat updates to latest Compose alpha

### CODE REVIEW

**Review by florina-muntenescu — APPROVED** [review]

**Review by objcode — COMMENTED** [review]
LGTM

**Comment by ChhotuKumar87** [comment]
/scripts/libs.versions.toml

**Comment by ChhotuKumar87** [comment]
/scripts/libs.versions.toml

**Review by dick-kane — COMMENTED** [review]
Ok

**Pull request merged**
