### PR TITLE
[JetNews] Add gif of JetNews working on large screens

### PR DESCRIPTION
**Pull request by tsuharesu**
Also fix some links on README

### CODE REVIEW

**Review by riggaroo — COMMENTED** [review]
Is it possible to resize the gif animation?

**Comment by tsuharesu** [comment]
@riggaroo the recording was 2560px wide, but I felt that was too much for a gif.  I updated with a larger gif but still not full size.

**Comment by riggaroo** [comment]
This will increase the size of download of the whole repository though - I see its increased from 8mb to 41mb, I think it should be resized or referenced in a different way to not bloat the download of the whole repository.

**Comment by tsuharesu** [comment]
If Github displays videos, that would be the best. Gifs are too large for the quality. The video is only 6MB.

**Comment by JolandaVerhoef** [comment]
I agree the gif is too large for this repository. Would a screenshot showing Jetnews on different sized devices work instead?

**Review by riggaroo — APPROVED** [review]

**Review by alexvanyo — APPROVED** [review]

**Comment by noelknaepen** [comment]
> Also fix some links on README

Good point

**Comment by noelknaepen** [comment]
> Also fix some links on README

https://github.com/android/compose-samples/pull/789##discussion_r1326983955

**Pull request merged**
